name: Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x]
    name: Node v${{ matrix.node-version }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: install
        run: yarn --immutable
      - name: build
        run: yarn build:js
      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1
      - name: run tests
        run: yarn test-ci-partial:parallel --max-workers ${{ steps.cpu-cores.outputs.count }}

  test-jasmine:
    name: Node LTS on ${{ inputs.os }} using jest-jasmine2
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: install
        run: yarn --immutable
      - name: build
        run: yarn build:js
      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1
      - name: run tests using jest-jasmine
        run: yarn jest-jasmine-ci --max-workers ${{ steps.cpu-cores.outputs.count }}
